In [12]:
import pandas as pd
import numpy as np

In [20]:
linA_genes = pd.read_csv('lineage_11_10_2021_1536.results.csv')

In [21]:
linA_genes

,Gene,Non-unique Gene name,Annotation,Number_pos_present_in,Number_neg_present_in,Number_pos_not_present_in,Number_neg_not_present_in,Sensitivity,Specificity,Odds_ratio,Naive_p,Bonferroni_p,Benjamini_H_p,Max_Pairwise_comparisons,Max_supporting_pairs,Max_opposing_pairs,Best_pairwise_comp_p,Worst_pairwise_comp_p
0,group_1024,NaN,Phosphoribosyl transferase domain protein,269,28,29,93,90.268456,76.859504,30.809113,1.492311e-41,5.254428e-38,1.751476e-38,14,13,4,0.001831,0.179565
1,group_1706,NaN,hypothetical protein,269,28,29,93,90.268456,76.859504,30.809113,1.492311e-41,5.254428e-38,1.751476e-38,14,13,4,0.001831,0.179565
2,group_1483,NaN,hypothetical protein,29,93,269,28,9.731544,23.140496,0.032458,1.492311e-41,5.254428e-38,1.751476e-38,14,4,13,0.001831,0.179565
3,group_2315,NaN,hypothetical protein,51,97,247,24,17.114094,19.834711,0.051087,2.464226e-34,8.676538e-31,2.169135e-31,16,5,13,0.021271,0.210114
4,group_2283,NaN,hypothetical protein,38,87,260,34,12.751678,28.099174,0.057118,6.944336e-32,2.445101e-28,4.890201e-29,10,5,6,0.753906,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,group_1549,tbpB_2,Transferrin-binding protein 2,3,5,295,116,1.006711,95.867769,0.235932,4.801767e-02,1.000000e+00,2.940352e-01,5,3,2,1.000000,1.000000
575,group_1130,NaN,hypothetical protein,279,119,19,2,93.624161,1.652893,0.246793,4.849826e-02,1.000000e+00,2.964624e-01,6,1,5,0.218750,0.218750
576,group_2539,NaN,hypothetical protein,38,25,260,96,12.751678,79.338843,0.561231,4.953061e-02,1.000000e+00,3.022483e-01,9,7,4,0.179688,1.000000
577,moeB,NaN,Molybdopterin-synthase adenylyltransferase,283,108,15,13,94.966443,10.743802,2.270988,4.976542e-02,1.000000e+00,3.031558e-01,9,7,6,0.179688,0.507812
578,group_2785,NaN,hypothetical protein,20,2,278,119,6.711409,98.347107,4.280576,4.988916e-02,1.000000e+00,3.033847e-01,7,5,2,0.453125,0.453125

In [100]:
filt_linA = linA_genes[linA_genes['Benjamini_H_p'] < 0.01]

In [101]:
#filt_linA.to_csv('lineage_scoary_185_Ben01.csv')

In [102]:
filt_linA

,Gene,Non-unique Gene name,Annotation,Number_pos_present_in,Number_neg_present_in,Number_pos_not_present_in,Number_neg_not_present_in,Sensitivity,Specificity,Odds_ratio,Naive_p,Bonferroni_p,Benjamini_H_p,Max_Pairwise_comparisons,Max_supporting_pairs,Max_opposing_pairs,Best_pairwise_comp_p,Worst_pairwise_comp_p
0,group_1024,NaN,Phosphoribosyl transferase domain protein,269,28,29,93,90.268456,76.859504,30.809113,1.492311e-41,5.254428e-38,1.751476e-38,14,13,4,0.001831,0.179565
1,group_1706,NaN,hypothetical protein,269,28,29,93,90.268456,76.859504,30.809113,1.492311e-41,5.254428e-38,1.751476e-38,14,13,4,0.001831,0.179565
2,group_1483,NaN,hypothetical protein,29,93,269,28,9.731544,23.140496,0.032458,1.492311e-41,5.254428e-38,1.751476e-38,14,4,13,0.001831,0.179565
3,group_2315,NaN,hypothetical protein,51,97,247,24,17.114094,19.834711,0.051087,2.464226e-34,8.676538e-31,2.169135e-31,16,5,13,0.021271,0.210114
4,group_2283,NaN,hypothetical protein,38,87,260,34,12.751678,28.099174,0.057118,6.944336e-32,2.445101e-28,4.890201e-29,10,5,6,0.753906,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,group_227,NaN,Type II transport protein GspH,43,4,255,117,14.429530,96.694215,4.932353,5.502765e-04,1.000000e+00,7.020013e-03,12,11,3,0.006348,0.145996
276,group_1208,NaN,hypothetical protein,269,120,29,1,90.268456,0.826446,0.077299,5.579117e-04,1.000000e+00,7.091723e-03,8,1,7,0.070312,0.070312
277,group_1438,NaN,hypothetical protein,287,105,11,16,96.308725,13.223140,3.975758,7.131784e-04,1.000000e+00,9.032738e-03,10,4,6,0.753906,0.753906
278,group_1906,NaN,hypothetical protein,210,104,88,17,70.469799,14.049587,0.390079,7.567630e-04,1.000000e+00,9.550403e-03,14,6,11,0.057373,0.790527
279,group_619,NaN,hypothetical protein,118,70,180,51,39.597315,42.148760,0.477619,7.709818e-04,1.000000e+00,9.695096e-03,16,10,11,0.210114,0.454498

In [25]:
filt_linA['Gene']

0      group_1024
1      group_1706
2      group_1483
3      group_2315
4      group_2283
          ...
392    group_2033
393    group_1858
394    group_1859
395          hprA
396     group_185
Name: Gene, Length: 397, dtype: object

In [26]:
data = pd.read_csv('gene_oneHotEncoding.csv')

In [27]:
lineage = pd.read_csv('lineages.csv',sep='\t', index_col = 0)
lineage = lineage.set_index(data.index)

In [28]:
datafilt = data[filt_linA['Gene']].join(lineage)

In [74]:
datafilt

,group_1024,group_1706,group_1483,group_2315,group_2283,group_2316,group_410,group_789,group_948,aplIM_2,...,group_1885,group_944,group_300,group_1011,group_2033,group_1858,group_1859,hprA,group_185,lineage
0,0,0,1,1,0,1,1,1,0,1,...,1,0,1,0,1,0,0,1,0,1
1,1,1,0,0,0,0,1,1,0,1,...,1,0,1,0,1,1,1,1,0,1
2,1,1,0,1,1,1,1,1,0,1,...,0,0,1,0,1,1,1,1,0,1
3,1,1,0,0,0,0,1,1,0,1,...,1,0,1,0,1,1,1,1,0,1
4,1,1,0,0,0,0,1,1,0,1,...,1,0,1,0,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,1,1,0,0,0,1,1,1,0,1,...,1,0,1,0,1,1,1,1,0,0
415,1,1,0,1,1,1,1,1,0,1,...,1,0,1,0,1,0,0,1,0,0
416,1,1,0,0,0,0,1,1,0,1,...,1,0,1,0,1,0,0,1,0,0
417,0,0,1,1,0,1,0,0,1,0,...,1,0,1,0,1,0,0,1,0,0
418,0,0,1,1,1,1,0,0,0,1,...,1,0,1,0,1,1,1,1,0,0

In [75]:
n = 120

In [76]:
from sklearn.model_selection import train_test_split
trainf, testf = train_test_split(datafilt, test_size = 0.2)
X_trainf = trainf.iloc[:,:n-1].to_numpy()
X_testf = testf.iloc[:,:n-1].to_numpy()
y_trainf = trainf['lineage'].to_numpy()
y_testf = testf['lineage'].to_numpy()

In [77]:
from sklearn import svm

In [78]:
#SVM train con le feature selezionate
linear_svc = svm.SVC(kernel='linear')
linear_svc.fit(X_trainf, y_trainf)

SVC(kernel='linear')

In [79]:
from sklearn import metrics
y_predf = linear_svc.predict(X_testf)
metrics.confusion_matrix(y_testf, y_predf)

array([[ 7, 17],
       [ 4, 56]])

In [80]:
metrics.accuracy_score(y_testf, y_predf)

0.75

In [81]:
from sklearn import preprocessing
X_trainf_normalized = preprocessing.normalize(X_trainf, norm='l2')

X_testf_normalized = preprocessing.normalize(X_testf, norm='l2')

In [82]:
##Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty ='l2').fit(X_trainf_normalized, y_trainf)
y_predf = clf.predict(X_testf_normalized)
metrics.confusion_matrix(y_testf, y_predf)

array([[ 6, 18],
       [ 3, 57]])

In [83]:
metrics.accuracy_score(y_testf, y_predf)

0.75

In [84]:
#Cross Validation
from sklearn.model_selection import cross_val_score
Xf = datafilt.iloc[:,:-1].to_numpy()
yf = datafilt['lineage'].to_numpy()
X_trainf_normalized = preprocessing.normalize(Xf, norm='l2')

In [85]:

scores = cross_val_score(LogisticRegression(penalty ='l2'), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.71 accuracy with a standard deviation of 0.06

In [86]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_trainf, y_trainf)
y_predf = rf.predict(X_testf)

In [87]:
rf.score(X_testf, y_testf, sample_weight=None)

0.7738095238095238

In [88]:
metrics.confusion_matrix(y_testf, y_predf)

array([[ 6, 18],
       [ 1, 59]])

In [89]:
#Cross Validation
from sklearn.model_selection import cross_val_score
Xf = datafilt.iloc[:,:-1].to_numpy()
yf = datafilt['lineage'].to_numpy()
X_trainf_normalized = preprocessing.normalize(Xf, norm='l2')
scores = cross_val_score(RandomForestClassifier(), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.69 accuracy with a standard deviation of 0.09

In [90]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

In [96]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_trainf, y_trainf)

KNeighborsClassifier(n_neighbors=3)

In [97]:
y_predf = neigh.predict(X_testf)
metrics.confusion_matrix(y_testf, y_predf)

array([[ 7, 17],
       [ 3, 57]])

In [98]:
neigh.score(X_testf, y_testf, sample_weight=None)

0.7619047619047619

In [99]:
scores = cross_val_score(KNeighborsClassifier(n_neighbors=3), X_trainf_normalized, yf, cv=7)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.72 accuracy with a standard deviation of 0.10